# Licensed under The MIT License. See LICENSE for more details.

FFA = 0
COOP_EDIT = 1
TEAM = 2
INSTAGIB = 3
INSTAGIB_TEAM = 4
EFFICIENCY = 5
EFFICIENCY_TEAM = 6
TACTICS = 7
TACTICS_TEAM = 8
CAPTURE = 9
REGEN_CAPTURE = 10
CTF = 11
INSTA_CTF = 12
PROTECT = 13
INSTA_PROTECT = 14
HOLD = 15
INSTA_HOLD = 16
EFFICIENCY_CTF = 17
EFFICIENCY_PROTECT = 18
EFFICIENCY_HOLD = 19
DEMO_PLAYBACK = -1
SINGLE_PLAYER = -2
